# Generated by Django 4.0 on 2022-04-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='pictures')),
                ('des', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.AlterField(
            model_name='contect',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
