# Generated by Django 4.0 on 2022-04-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0005_love_leen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='love',
            new_name='owner',
        ),
        migrations.RenameModel(
            old_name='leen',
            new_name='worker',
        ),
    ]
