# Generated by Django 4.0 on 2022-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0006_rename_love_owner_rename_leen_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='dietplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('des', models.TextField()),
            ],
            options={
                'db_table': 'dietplan',
            },
        ),
    ]
