# Generated by Django 4.0 on 2022-05-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0009_sub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dietplan',
        ),
    ]
